Update deno.yml

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,43 +1,39 @@
-name: Test, Lint, Build and Deploy on Github Pages
+# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
+
+name: Node.js CI
 
 on:
   push:
-    branches: ["master", "main"]
-
-  # Позволяет запустить этот рабочий процесс вручную на вкладке Actions
-  workflow_dispatch:
-
-permissions:
-  contents: write
+    branches: [ "master" ]
+  pull_request:
+    branches: [ "master" ]
 
 jobs:
-  build-and-deploy:
+  build:
+
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
         node-version: [22.x]
+        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
-      - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm ci
+    - run: npm run build --if-present
+    - run: npm test
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
 
       # Устанавливаем зависимости
-      - name: Install dependencies
-        run: npm install
-
-      # Запускаем тесты и линтер
-      - name: Run tests and linter
-        run: npm run lint && npm test
-
-      # Собираем приложение
-      #- name: Build Application
-      #  run: npm run build
-
+      #- name: Install dependencies
+      #  run: npm install
       # Публикуем приложение на Github Pages
       #- name: Deploy to Github Pages
       #  uses: JamesIves/github-pages-deploy-action@4.2.1
@@ -58,6 +54,6 @@ jobs:
       #    commit-message: "Automatically publish Storybook"
 
       # Останавливаем выполнение строго при неудачных тестах
-      - name: Fail on failed tests
-        run: |
-          if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
+      # - name: Fail on failed tests
+      #  run: |
+      #    if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
